"""empty message

Revision ID: 7cb44cf49925
Revises: f0ba4809d4fe
Create Date: 2024-06-23 00:22:09.061419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cb44cf49925'
down_revision = 'f0ba4809d4fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=80), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('prix_u', sa.Float(), nullable=False),
    sa.Column('prix_t', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prix_t'),
    sa.UniqueConstraint('prix_u')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produits')
    # ### end Alembic commands ###
